inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - '.bundle/**/*'
    - 'config/boot.rb'
    - 'db/schema.rb'
    - 'lib/tasks/cucumber.rake'
    - 'features/support/paths.rb'
    - 'features/support/selectors.rb'
    - 'features/step_definitions/web_steps.rb'
  RunRailsCops: true
Style/Documentation:
  Enabled: false
